# Stormcraft Events Configuration
# Dynamic event system that spawns storm-themed objectives and encounters

events:
  # Global settings
  globalCooldown: 60              # Seconds between any events
  announceRadius: 900             # Blocks to announce events (nearby storm = within 900 blocks)
  useActionBar: true              # Use action bar for event updates
  useBossBar: true                # Use boss bar for boss health
  chatAnnouncements: true         # Broadcast boss spawn/death in chat

  # Storm zone spawn weights
  spawnZones:
    stormCore:
      minDistance: 0
      maxDistance: 50
      weight: 60
    stormPeriphery:
      minDistance: 50
      maxDistance: 150
      weight: 30
    stormInfluence:
      minDistance: 150
      maxDistance: 300
      weight: 10

  # Density-based spawning
  density:
    checkInterval: 30             # Seconds between density checks
    baseChance: 0.05              # 5% base spawn chance
    playerMultiplier: 0.1         # Additional chance per player (logarithmic)
    maxChance: 0.5                # Max 50% spawn chance

# Group-Based Dynamic Difficulty System
# Scales event difficulty and boss spawn chances based on player groups
difficulty:
  enabled: true

  # Player detection
  scan_radius: 50.0               # Blocks to scan for nearby players
  scan_interval: 100              # Ticks between scans (5 seconds)

  # Multiplier bonuses
  party_bonus_per_member: 0.3     # Bonus per party member
  max_party_bonus: 1.5            # Maximum party bonus
  proximity_bonus_per_player: 0.2 # Bonus per nearby non-party player
  max_proximity_bonus: 1.0        # Maximum proximity bonus
  wilderness_bonus: 0.5           # Bonus for being in wilderness (not town)
  storm_proximity_bonus: 0.5      # Bonus for being near active storm
  storm_proximity_radius: 300.0   # Distance to be "near" a storm

  # Safe zones
  respect_town_claims: true       # Towny/TAN claims reduce difficulty
  town_claim_multiplier: 0.5      # Multiply final difficulty by this in towns

  # Reward scaling
  reward_scaling_factor: 2.5      # How much multiplier affects rewards
  party_completion_bonus: 0.1     # 10% per party member
  max_party_completion_bonus: 0.5 # 50% max

  # Event type weights by threat level
  # Multiplier ranges: LOW (1.0-1.49), MEDIUM (1.5-1.99), HIGH (2.0-2.74), EXTREME (2.75+)
  weights:
    low:
      storm_surge: 60
      storm_rift: 30
      tempest_guardian: 10
      storm_titan: 0
      town_siege: 0
    medium:
      storm_surge: 40
      storm_rift: 35
      tempest_guardian: 20
      storm_titan: 5
      town_siege: 0
    high:
      storm_surge: 20
      storm_rift: 30
      tempest_guardian: 35
      storm_titan: 10
      town_siege: 5
    extreme:
      storm_surge: 10
      storm_rift: 20
      tempest_guardian: 40
      storm_titan: 20
      town_siege: 10

  # Event type configs
  types:
    STORM_SURGE:
      enabled: true
      weight: 30
      minPlayers: 1
      requiresStorm: true
      cooldown: 300                # 5 minutes
      duration: 120                # 2 minutes
      crystalCount: 5
      essenceReward: 50

    TEMPEST_GUARDIAN:
      enabled: true
      weight: 15
      minPlayers: 3
      requiresStorm: true
      cooldown: 1800               # 30 minutes
      mythicMobType: "TempestGuardian"  # MythicMobs mob name
      essenceReward: 200

    STORM_RIFT:
      enabled: true
      weight: 20
      minPlayers: 2
      requiresStorm: true
      cooldown: 900                # 15 minutes
      duration: 300                # 5 minutes
      waveCount: 5
      mobsPerWave: 10
      essenceReward: 150

    STORM_TITAN:
      enabled: true
      weight: 5
      minPlayers: 10
      requiresStorm: true
      stormIntensityMin: 80
      cooldown: 7200               # 2 hours
      mythicMobType: "StormTitan"
      essenceReward: 1000

    TOWN_SIEGE:
      enabled: true
      weight: 10
      minPlayers: 2                # Must be 2+ players in/near town
      requiresStorm: true          # Storm must be nearby
      stormProximity: 900          # Storm within 900 blocks (nearby storm)
      baseChance: 0.02             # 2% chance per check
      cooldown: 3600               # 1 hour per town
      duration: 600                # 10 minutes
      waveCount: 3
      mobsPerWave: 15
      allowOptOut: true            # Towns can disable via permission
      mobsCanBreakBlocks: true     # Allow mobs to break blocks during siege
